development:
  username: postgres
  adapter: postgresql
  database: iphotographisme_development
  host: localhost

test:
  username: postgres
  adapter: postgresql
  database: iphotographisme_test
  host: localhost

production:
  username: postgres
  adapter: postgresql
  database: iphotographisme_production